# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# https://www.tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
# https://github.com/AndrewAnnex/SpiceyPy/blob/master/appveyor.yml
build: false

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      PLAT_NAME: "win-amd64"
      PY_TAG: "cp35"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      PLAT_NAME: "win-amd64"
      PY_TAG: "cp36"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      PLAT_NAME: "win-amd64"
      PY_TAG: "cp37"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install pytest"
  - "%PYTHON%/Scripts/pip.exe install packaging"

test_script:
  - "%PYTHON%/Scripts/pytest"
